/* 
CREATE TABLE studentStatus (
	id serial PRIMARY KEY,
	status varchar(50) NOT NULL UNIQUE
);
*/
/*
INSERT INTO studentstatus (status)
VALUES ('pending');
*/
/*
INSERT INTO studentstatus (status)
VALUES ('awaiting'),('active'),('suspended'),('droped out'),('graduated');
*/
/*
CREATE TABLE students (
	id serial PRIMARY KEY,
	name varchar(50) NOT NULL,
	surname varchar(50) NOT NULL,
	email varchar(255) NOT NULL UNIQUE,
	phone varchar(50) NOT NULL UNIQUE
)
*/
/*
ALTER TABLE students 
ADD statusid int references studentstatus (id);
*/
/*
INSERT INTO students (name, surname, email, phone, statusid)
VALUES ('Claudio','Rosso','crosso@students.soyhenry.com','+451122222222',1);
*/
/*
ALTER TABLE students
ALTER COLUMN statusid SET DEFAULT 1;
*/
/*
INSERT INTO students (name, surname, email, phone)
VALUES ('Santiago','Fernandez','sfernandez@students.soyhenry.com','+451122222221'),
('Pedro','Moran','pmoran@students.soyhenry.com','+451122222223');
*/
/*
SELECT *
FROM students;
*/
/*
SELECT *
FROM students
WHERE id = 1;
*/
/*
SELECT *
FROM students
WHERE name = 'Claudio';
*/
/*
SELECT *
FROM students
WHERE UPPER(name) = 'CLAUDIO';
*/
/*
SELECT id, name, email
FROM students
WHERE name ilike 'c%';
*/
/*
SELECT s.id as id, s.name as name, s.surname as surname, ss.status as status
FROM students as s
JOIN studentstatus as ss ON s.statusid = ss.id
ORDER BY s.surname DESC, s.name;
*/
/*
UPDATE students
SET statusid = 2
WHERE id = 1;
*/
/*
SELECT s.id as id, s.name as name, s.surname as surname, ss.status as status
FROM students as s
JOIN studentstatus as ss ON s.statusid = ss.id
WHERE ss.id = 2
ORDER BY s.surname DESC, s.name;
*/
/*
SELECT COUNT(*)
FROM students as s
JOIN studentstatus as ss ON s.statusid = ss.id
WHERE ss.id = 1;
*/
/*
SELECT status, COUNT(s.id)
FROM students as s
RIGHT JOIN studentstatus as ss ON s.statusid = ss.id
GROUP BY status, ss.id
ORDER BY ss.id;
*/
/*
DELETE FROM students WHERE id=3;
*/
SELECT *
FROM students
WHERE statusid NOT IN (
	SELECT id
	FROM studentstatus
	WHERE id = 1
)